version: '3.9'
services:
  db:
   image: mysql:5.7.22
   restart: always
   environment:
     MYSQL_DATABASE: ${DB_NAME}
     MYSQL_USER: ${DB_USERNAME}
     MYSQL_PASSWORD: ${DB_PASSWORD}
     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
   volumes:
    - .dbdata:/var/lib/mysql
   ports:
     - 3306:3306