version: '3.9'
services:
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u${DB_USERNAME}", "-p${DB_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 4000:4000
    environment:
      DBHOST: ${DB_HOST}
      DBUSER: ${DB_USERNAME}
      DBPASSWORD:  ${DB_PASSWORD}
      DBPORT: 3306
      DBNAME: ${DB_NAME}

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - 3000:80
    environment:
      NODE_ENV: development
      BACKEND_URL: http://localhost:4000
volumes:
  dbdata: