apiVersion: v1
data:
  dbname: taskmanager # Create the database in the MySQL pod container.
                      # Exec into the MySQL pod container and run the following command:
                      # mysql -u root -p
                      # Enter the password value encoded in myqsl-secret resource: password
                      # - CREATE DATABASE taskmanager;
  host: mysql.<namespace>.svc.cluster.local
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: backend-cm
  namespace: <namespace>