# This file contains the secret for mysql root password which is used in the mysql and backend deployments.
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: <namespace>
type: Opaque
data:
  rootpassword: cGFzc3dvcmQ=  # base64 encoded value of 'password'